/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package procon.vista;

import java.awt.GridBagConstraints;
import java.awt.Insets;
import javax.swing.JLabel;

/**
 *
 * @author furid
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        this.setTitle("El Productor y el Consumidor");
        lblTitle.setText(getTitle());
    }
    
    
    protected void AddLabels(javax.swing.JPanel panel, int cant){
        GridBagConstraints constraints = new GridBagConstraints();
        constraints.anchor = GridBagConstraints.WEST;
        constraints.insets = new Insets(5, 5, 5, 5);
        int x = 0, y = 0;        
        for (int i = 1; i <= cant; i++) {
            constraints.gridx = x;
            constraints.gridy = y;  
            javax.swing.JLabel lbl = new JLabel(String.valueOf(i));            
            panel.add(lbl, constraints);            
            if((i%10)==0){
                x=0;
                y++;
            }else x++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        btnStart = new javax.swing.JButton();
        pnlAlmacen = new javax.swing.JPanel();
        lblTitleAlmacen = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlContentAlmacen = new javax.swing.JPanel();
        pnlConsumidor = new javax.swing.JPanel();
        lblTitleConsumidor = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pnlContentConsumidor = new javax.swing.JPanel();
        pnlProductor = new javax.swing.JPanel();
        lblTitleProductor = new javax.swing.JLabel();
        pnlScrollContentProductor = new javax.swing.JScrollPane();
        pnlContentProductor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        setForeground(java.awt.Color.white);
        setMinimumSize(new java.awt.Dimension(999, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(999, 600));

        pnlHeader.setToolTipText("");

        lblTitle.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTitle.setText("Titulo");

        btnStart.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnStart.setText("Iniciar");

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle)
                    .addComponent(btnStart))
                .addGap(34, 34, 34))
        );

        pnlAlmacen.setBackground(new java.awt.Color(51, 51, 51));
        pnlAlmacen.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        pnlAlmacen.setMaximumSize(new java.awt.Dimension(325, 530));
        pnlAlmacen.setMinimumSize(new java.awt.Dimension(325, 530));
        pnlAlmacen.setPreferredSize(new java.awt.Dimension(325, 530));

        lblTitleAlmacen.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTitleAlmacen.setForeground(new java.awt.Color(255, 255, 255));
        lblTitleAlmacen.setText("Almacen");

        pnlContentAlmacen.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        pnlContentAlmacen.setMaximumSize(new java.awt.Dimension(314, 211));
        pnlContentAlmacen.setMinimumSize(new java.awt.Dimension(314, 211));
        pnlContentAlmacen.setLayout(new java.awt.GridBagLayout());
        jScrollPane1.setViewportView(pnlContentAlmacen);

        javax.swing.GroupLayout pnlAlmacenLayout = new javax.swing.GroupLayout(pnlAlmacen);
        pnlAlmacen.setLayout(pnlAlmacenLayout);
        pnlAlmacenLayout.setHorizontalGroup(
            pnlAlmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAlmacenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAlmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitleAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        pnlAlmacenLayout.setVerticalGroup(
            pnlAlmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAlmacenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitleAlmacen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(291, Short.MAX_VALUE))
        );

        pnlConsumidor.setBackground(new java.awt.Color(51, 51, 51));
        pnlConsumidor.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        pnlConsumidor.setMaximumSize(new java.awt.Dimension(325, 530));
        pnlConsumidor.setMinimumSize(new java.awt.Dimension(325, 530));
        pnlConsumidor.setPreferredSize(new java.awt.Dimension(325, 530));

        lblTitleConsumidor.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTitleConsumidor.setForeground(new java.awt.Color(255, 255, 255));
        lblTitleConsumidor.setText("Consumidor");

        pnlContentConsumidor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        pnlContentConsumidor.setMaximumSize(new java.awt.Dimension(314, 211));
        pnlContentConsumidor.setMinimumSize(new java.awt.Dimension(314, 211));
        pnlContentConsumidor.setLayout(new java.awt.GridBagLayout());
        jScrollPane2.setViewportView(pnlContentConsumidor);

        javax.swing.GroupLayout pnlConsumidorLayout = new javax.swing.GroupLayout(pnlConsumidor);
        pnlConsumidor.setLayout(pnlConsumidorLayout);
        pnlConsumidorLayout.setHorizontalGroup(
            pnlConsumidorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsumidorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlConsumidorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitleConsumidor, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        pnlConsumidorLayout.setVerticalGroup(
            pnlConsumidorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsumidorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitleConsumidor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(297, Short.MAX_VALUE))
        );

        pnlProductor.setBackground(new java.awt.Color(51, 51, 51));
        pnlProductor.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        pnlProductor.setForeground(new java.awt.Color(255, 255, 255));
        pnlProductor.setMaximumSize(new java.awt.Dimension(325, 530));
        pnlProductor.setMinimumSize(new java.awt.Dimension(325, 530));

        lblTitleProductor.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTitleProductor.setForeground(new java.awt.Color(255, 255, 255));
        lblTitleProductor.setText("Productor");

        pnlScrollContentProductor.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        pnlContentProductor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        pnlContentProductor.setMaximumSize(new java.awt.Dimension(314, 211));
        pnlContentProductor.setMinimumSize(new java.awt.Dimension(314, 211));
        pnlContentProductor.setLayout(new java.awt.GridBagLayout());
        pnlScrollContentProductor.setViewportView(pnlContentProductor);

        javax.swing.GroupLayout pnlProductorLayout = new javax.swing.GroupLayout(pnlProductor);
        pnlProductor.setLayout(pnlProductorLayout);
        pnlProductorLayout.setHorizontalGroup(
            pnlProductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlProductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitleProductor, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlScrollContentProductor, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        pnlProductorLayout.setVerticalGroup(
            pnlProductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitleProductor)
                .addGap(18, 18, 18)
                .addComponent(pnlScrollContentProductor, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(286, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlProductor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlAlmacen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlConsumidor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(15, 15, 15))
                    .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlAlmacen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlConsumidor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlProductor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStart;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitleAlmacen;
    private javax.swing.JLabel lblTitleConsumidor;
    private javax.swing.JLabel lblTitleProductor;
    private javax.swing.JPanel pnlAlmacen;
    private javax.swing.JPanel pnlConsumidor;
    public javax.swing.JPanel pnlContentAlmacen;
    public javax.swing.JPanel pnlContentConsumidor;
    public javax.swing.JPanel pnlContentProductor;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlProductor;
    public javax.swing.JScrollPane pnlScrollContentProductor;
    // End of variables declaration//GEN-END:variables
}
